name: deploy-docs
on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn deploy
# Maybe we need a secret here